#!/bin/sh
#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# chkconfig: 35 95 1
usage="Usage: datasophon-worker (start|stop|restart) <installPath> "

if [ $# -lt 2 ]; then
  echo $usage
  exit 1
fi

startStop=$1
INSTALL_PATH=$2
export $INSTALL_PATH
# 环境变量

case $startStop in
  (start)
    sh $INSTALL_PATH/datasophon-worker/bin/datasophon-worker.sh start
    ;;
  (stop)
    sh $INSTALL_PATH/datasophon-worker/bin/datasophon-worker.sh stop
      ;;
  (status)
    sh $INSTALL_PATH/datasophon-worker/bin/datasophon-worker.sh status
      ;;
  (restart)
    sh $INSTALL_PATH/datasophon-worker/bin/datasophon-worker.sh restart
      ;;
  (*)
    echo $usage
    exit 1
    ;;

esac

echo "End $startStop $command."